services:
  backend:
    build:
      context: .
      dockerfile: ./backend-docker/Dockerfile
    container_name: iot_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend-overrides:ro
    environment:
      - APP_PORT=8000

  frontend:
    build:
      context: .
      dockerfile: ./frontend-docker/Dockerfile
    container_name: iot_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://127.0.0.1:8000/api
    depends_on:
      - backend
